apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels: 
        app: hello-world  
    spec:                      
      containers: 
      - name: hello-world 
        image: hello-world-image:v1 
        ports:
        - containerPort: 3000
