apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-docker-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels: 
        app: hello-docker  
    spec:                      
      containers: 
      - name: hello-docker 
        image: hello-docker:v1 
        ports:
        - containerPort: 3000
