apiVersion: v1
kind: Service
metadata: 
  name: hello-docker
  labels:
    app: hello-docker
spec: 
  ports:    
     - protocol: TCP
       port: 8085
       targetPort: 8080
  selector: 
      app: hello-docker  
  type: NodePort
